Repository CA-G12/Lorem-App, pull requests merged in 2022-08, with the labels that each got.

#9 6 sign up page
  .gitignore
  public/index.html
  public/pages/signup/index.html
  public/pages/signup/script.js
  public/pages/signup/style.css
  server/app.js
  server/controllers/index.js
  server/controllers/sign-up.js
  server/database/config/connection.js
  server/database/queries/index.js
  server/database/queries/insertData.js
  server/routes/index.js
  server/routes/sign-up.js
Labels: Waiting Review

#13 generate token almost ready :)
  public/index.html
  public/pages/lorem/index.html
  server/app.js
  server/controllers/signIn.js
  server/database/queries/insertData.js
  server/jwt/index.js
Labels: Waiting Review

#14 10 sign up stage 2
  public/pages/lorem/index.html
  public/pages/lorem/script.js
  public/pages/lorem/style.css
  public/pages/signin/script.js
  public/pages/signup/script.js
  server/controllers/sign-up.js
  server/controllers/signIn.js
  server/database/queries/insertData.js
  server/jwt/index.js
Labels: In Progress

#17 16 generate verify token stage 2
  public/pages/signin/index.html
  public/pages/signin/script.js
  server/app.js
  server/controllers/500.js
  server/controllers/signIn.js
  server/database/queries/signInQuery.js
  server/jwt/index.js
  server/routes/index.js
  server/routes/lorem.js
Labels: Marged

#20 fixed the login submit fetch, some package json issues
  public/pages/signin/script.js
  server/controllers/signIn.js
  server/database/queries/signInQuery.js
  server/routes/lorem.js
Labels: Waiting Review

#22 15 add lorem function
  public/pages/lorem/index.html
  public/pages/lorem/script.js
  public/pages/lorem/style.css
  public/pages/signin/style.css
  public/pages/signup/script.js
  server/controllers/getLorem.js
  server/controllers/index.js
  server/controllers/insertLorem.js
  server/controllers/sign-up.js
  server/controllers/signIn.js
  server/database/queries/getLorem.js
  server/database/queries/index.js
  server/database/queries/insertData.js
  server/database/queries/insertLorem.js
  server/jwt/index.js
  server/routes/getLorem.js
  server/routes/index.js
  server/routes/lorem.js
Labels: Waiting Review
